/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Game.CLI;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danielh
 */
public class MainWindow extends javax.swing.JFrame {

	/**
	 * Creates new form MainWindow
	 */
	
	public Generala generala = new Generala();
	
	public MainWindow()
	{
		initComponents();
		this.setLocationRelativeTo(this);
		this.setMinimumSize(this.getPreferredSize());
		
		generala.jugadores = PlayersWindow.getPlayers();
		
		generala.tablaPuntajes = new int[generala.jugadores.length][12];
		
		System.out.println("players = "+Arrays.toString(generala.jugadores));
		
		DefaultTableModel defaultTableModel = new DefaultTableModel();
		
		tablaPuntajes.setModel(defaultTableModel);
		
		for (int i = 0; i < generala.jugadores.length; i++)
		{
			generala.tablaPuntajes[i][0] = i;
			
			defaultTableModel.addColumn(generala.jugadores[i]);
		}
		
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING:
	 * Do NOT modify this code. The content of this method is always regenerated by the
	 * Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        holder1 = new javax.swing.JLabel();
        holder2 = new javax.swing.JLabel();
        holder3 = new javax.swing.JLabel();
        holder4 = new javax.swing.JLabel();
        holder5 = new javax.swing.JLabel();
        tirar = new javax.swing.JLabel();
        dicePanel = new javax.swing.JPanel();
        dice1 = new javax.swing.JLabel();
        dice2 = new javax.swing.JLabel();
        dice3 = new javax.swing.JLabel();
        dice4 = new javax.swing.JLabel();
        dice5 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        panelPuntajes = new javax.swing.JScrollPane();
        tablaPuntajes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        leftPanel.setBackground(new java.awt.Color(0, 255, 153));

        holder1.setBackground(new java.awt.Color(255, 255, 255));
        holder1.setForeground(new java.awt.Color(255, 255, 255));
        holder1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        holder1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/diceHolder.png"))); // NOI18N

        holder2.setBackground(new java.awt.Color(255, 255, 255));
        holder2.setForeground(new java.awt.Color(255, 255, 255));
        holder2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        holder2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/diceHolder.png"))); // NOI18N

        holder3.setBackground(new java.awt.Color(255, 255, 255));
        holder3.setForeground(new java.awt.Color(255, 255, 255));
        holder3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        holder3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/diceHolder.png"))); // NOI18N

        holder4.setBackground(new java.awt.Color(255, 255, 255));
        holder4.setForeground(new java.awt.Color(255, 255, 255));
        holder4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        holder4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/diceHolder.png"))); // NOI18N

        holder5.setBackground(new java.awt.Color(255, 255, 255));
        holder5.setForeground(new java.awt.Color(255, 255, 255));
        holder5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        holder5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/diceHolder.png"))); // NOI18N

        tirar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tirar.setText("Tirar dados");
        tirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tirarMouseClicked(evt);
            }
        });

        dicePanel.setBackground(new java.awt.Color(0, 255, 153));
        dicePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dice1.setBackground(new java.awt.Color(255, 255, 255));
        dice1.setForeground(new java.awt.Color(255, 255, 255));
        dice1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dice1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dice1.setMaximumSize(new java.awt.Dimension(50, 50));
        dice1.setMinimumSize(new java.awt.Dimension(50, 50));
        dice1.setPreferredSize(new java.awt.Dimension(50, 50));
        dicePanel.add(dice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        dice2.setBackground(new java.awt.Color(255, 255, 255));
        dice2.setForeground(new java.awt.Color(255, 255, 255));
        dice2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dice2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dice2.setMaximumSize(new java.awt.Dimension(50, 50));
        dice2.setMinimumSize(new java.awt.Dimension(50, 50));
        dice2.setPreferredSize(new java.awt.Dimension(50, 50));
        dicePanel.add(dice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        dice3.setBackground(new java.awt.Color(255, 255, 255));
        dice3.setForeground(new java.awt.Color(255, 255, 255));
        dice3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dice3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dice3.setMaximumSize(new java.awt.Dimension(50, 50));
        dice3.setMinimumSize(new java.awt.Dimension(50, 50));
        dice3.setPreferredSize(new java.awt.Dimension(50, 50));
        dicePanel.add(dice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        dice4.setBackground(new java.awt.Color(255, 255, 255));
        dice4.setForeground(new java.awt.Color(255, 255, 255));
        dice4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dice4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dice4.setMaximumSize(new java.awt.Dimension(50, 50));
        dice4.setMinimumSize(new java.awt.Dimension(50, 50));
        dice4.setPreferredSize(new java.awt.Dimension(50, 50));
        dicePanel.add(dice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        dice5.setBackground(new java.awt.Color(255, 255, 255));
        dice5.setForeground(new java.awt.Color(255, 255, 255));
        dice5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dice5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dice5.setMaximumSize(new java.awt.Dimension(50, 50));
        dice5.setMinimumSize(new java.awt.Dimension(50, 50));
        dice5.setPreferredSize(new java.awt.Dimension(50, 50));
        dicePanel.add(dice5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(holder1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(leftPanelLayout.createSequentialGroup()
                                .addComponent(holder2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(holder3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(holder4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tirar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(holder5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(dicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tirar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(holder1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(holder2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(holder3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(holder4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(holder5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));

        panelPuntajes.setBackground(new java.awt.Color(255, 255, 255));

        tablaPuntajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        panelPuntajes.setViewportView(tablaPuntajes);

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPuntajes, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPuntajes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
    private void tirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tirarMouseClicked

        generala.dados = generala.lanzar(5);
        int[] originalDice = generala.dados;
        setDiceIcons(originalDice);
    }//GEN-LAST:event_tirarMouseClicked
	
	private void setDiceIcons(int[] originalDice)
	{
		int[] dados = generala.dados;
		
		Arrays.sort(dados);
		
		JLabel[] dice = {dice1,dice2,dice4,dice3,dice5};
		JLabel[] holders = {holder1,holder2,holder3,holder4,holder5};
		
		for (int i = 0, takenHolders = 0; i < 5; i++)
		{
			switch (dados[i]) {
				case 0:
					dice[i].setIcon(null);
					holders[takenHolders].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/d"+originalDice[takenHolders]+".png")));
					break;
				case 1:
					dice[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/d1.png")));
					break;
				case 2:
					dice[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/d2.png")));
					break;
				case 3:
					dice[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/d3.png")));
					break;
				case 4:
					dice[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/d4.png")));
					break;
				case 5:
					dice[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/d5.png")));
					break;
				case 6:
					dice[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/d6.png")));
					break;
			}
		}
	}
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel dice1;
    private javax.swing.JLabel dice2;
    private javax.swing.JLabel dice3;
    private javax.swing.JLabel dice4;
    private javax.swing.JLabel dice5;
    private javax.swing.JPanel dicePanel;
    private javax.swing.JLabel holder1;
    private javax.swing.JLabel holder2;
    private javax.swing.JLabel holder3;
    private javax.swing.JLabel holder4;
    private javax.swing.JLabel holder5;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JScrollPane panelPuntajes;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTable tablaPuntajes;
    private javax.swing.JLabel tirar;
    // End of variables declaration//GEN-END:variables
}
