/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author danielh
 */
public class SelectionWindow extends javax.swing.JFrame
{
	private MainWindow mainWindow;
	
	public boolean isOpen;
	
	public Generala generala = MainWindow.generala;
	
	public int jugador, turno;
	
	public int[] seleccionables;

	public SelectionWindow(MainWindow mainWindow)
	{
		this.mainWindow = mainWindow;
		
		initComponents();
		
		this.setTitle("Puntajes");
		
		isOpen = true;
		
		this.setLocationRelativeTo(this);
		
		JRadioButton[] radioButtons = {al1,al2,al3,al4,al5,al6,aEscalera,aFull,aPoker,aGenerala};
		
		//System.out.println("jugadas posibles = "+Arrays.toString(generala.jugadasPosibles)); //DEBUG
		
		seleccionables = generala.getSeleccionable(generala.jugadasPosibles, jugador);
		
		//System.out.println("seleccionables = "+Arrays.toString(seleccionables)); //DEBUG
		
		for (int i = 0; i < radioButtons.length; i++)
		{
			buttonGroup.add(radioButtons[i]);
			
			switch (seleccionables[i+1])
			{
				case 1:
					radioButtons[i].setText("Puntuar "+generala.jugadasPosibles[i+1]+" en "+generala.tituloPuntajes[i+1]);
					break;
				case 0:
					radioButtons[i].setVisible(false);
					break;
				case -1:
					radioButtons[i].setText("Tachar "+generala.tituloPuntajes[i+1]);
					break;
			}
		}
	}
	
	/**
	 * This method is called from within the constructor to initialize the form. WARNING:
	 * Do NOT modify this code. The content of this method is always regenerated by the
	 * Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        al1 = new javax.swing.JRadioButton();
        al2 = new javax.swing.JRadioButton();
        al3 = new javax.swing.JRadioButton();
        al4 = new javax.swing.JRadioButton();
        al5 = new javax.swing.JRadioButton();
        al6 = new javax.swing.JRadioButton();
        aEscalera = new javax.swing.JRadioButton();
        aFull = new javax.swing.JRadioButton();
        aPoker = new javax.swing.JRadioButton();
        aGenerala = new javax.swing.JRadioButton();
        listo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        titulo.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Selecciona alguna opcion");

        al1.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        al1.setText("jRadioButton1");

        al2.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        al2.setText("jRadioButton2");

        al3.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        al3.setText("jRadioButton3");

        al4.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        al4.setText("jRadioButton4");

        al5.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        al5.setText("jRadioButton5");

        al6.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        al6.setText("jRadioButton6");

        aEscalera.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        aEscalera.setText("jRadioButton7");

        aFull.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        aFull.setText("jRadioButton8");

        aPoker.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        aPoker.setText("jRadioButton9");

        aGenerala.setFont(new java.awt.Font("Noto Sans", 0, 17)); // NOI18N
        aGenerala.setText("jRadioButton10");

        listo.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        listo.setText("Listo");
        listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addGap(0, 40, Short.MAX_VALUE)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(al6)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(al1)
                                            .addComponent(al2)
                                            .addComponent(al3)
                                            .addComponent(al4)
                                            .addComponent(al5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(aEscalera)
                                            .addComponent(aFull)
                                            .addComponent(aPoker)
                                            .addComponent(aGenerala))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE))))
                            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(al1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(al2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(al3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(al4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(aEscalera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aFull)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aPoker)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aGenerala)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(al5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(al6)
                .addGap(12, 12, 12)
                .addComponent(listo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	private int getSelected(JRadioButton[] rbtns)
	{
		for (int i = 0; i < rbtns.length; i++)
		{
			if (rbtns[i].isSelected())
			{
				return i+1;
			}
		}
		return -1;
	}
	
    private void listoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listoActionPerformed
		JRadioButton[] rbtns = {al1,al2,al3,al4,al5,al6,aEscalera,aFull,aPoker,aGenerala};
		
		if (getSelected(rbtns) >= 0)
		{
			int selected = getSelected(rbtns);
			
			//System.out.println("seleccionaste el boton "+selected); //DEBUG
			
			//System.out.println("SelectionWindow passing "+generala.tablaPuntajes[jugador][selected]); //DEBUG
			
			if (!generala.puntuar(generala.tituloPuntajes, generala.jugadasPosibles, generala.tablaPuntajes, jugador, selected))
			{
				JOptionPane.showMessageDialog(this, "esa casilla ya esta puntuada, por favor elija otra", "Aviso", JOptionPane.INFORMATION_MESSAGE);
			}
			else
			{
				mainWindow.updateScoreboard(generala.tablaPuntajes[jugador][selected], selected-1, jugador);

				mainWindow.clearDice();

				isOpen = false;
				
				this.dispose();
			}
		}
		else JOptionPane.showMessageDialog(this, "No hay seleccion", "", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_listoActionPerformed

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("GTK+".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//new SelectionWindow().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aEscalera;
    private javax.swing.JRadioButton aFull;
    private javax.swing.JRadioButton aGenerala;
    private javax.swing.JRadioButton aPoker;
    private javax.swing.JRadioButton al1;
    private javax.swing.JRadioButton al2;
    private javax.swing.JRadioButton al3;
    private javax.swing.JRadioButton al4;
    private javax.swing.JRadioButton al5;
    private javax.swing.JRadioButton al6;
    private javax.swing.JPanel bg;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton listo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
